-- Seed Data for Industrial Jobs HQ
-- Run this in Supabase SQL Editor after running schema.sql

-- Insert Companies
INSERT INTO companies (id, name, logo_url, website) VALUES
  ('c1000001-0000-0000-0000-000000000001', 'Acme Manufacturing', NULL, 'https://acme-manufacturing.com'),
  ('c1000001-0000-0000-0000-000000000002', 'RoboTech Solutions', NULL, 'https://robotech-solutions.com'),
  ('c1000001-0000-0000-0000-000000000003', 'Industrial Supply Co.', NULL, 'https://industrial-supply.com'),
  ('c1000001-0000-0000-0000-000000000004', 'Precision Tools Inc.', NULL, 'https://precision-tools.com'),
  ('c1000001-0000-0000-0000-000000000005', 'Midwest Packaging Solutions', NULL, 'https://midwest-packaging.com'),
  ('c1000001-0000-0000-0000-000000000006', 'Heavy Machinery Corp', NULL, 'https://heavy-machinery.com'),
  ('c1000001-0000-0000-0000-000000000007', 'AutoMate Industries', NULL, 'https://automate-industries.com'),
  ('c1000001-0000-0000-0000-000000000008', 'Steel Dynamics Sales', NULL, 'https://steel-dynamics.com'),
  ('c1000001-0000-0000-0000-000000000009', 'Great Lakes Equipment', NULL, 'https://greatlakes-equipment.com'),
  ('c1000001-0000-0000-0000-000000000010', 'Buckeye Industrial', NULL, 'https://buckeye-industrial.com'),
  ('c1000001-0000-0000-0000-000000000011', 'Motor City Automation', NULL, 'https://motorcity-automation.com'),
  ('c1000001-0000-0000-0000-000000000012', 'Hoosier Manufacturing', NULL, 'https://hoosier-mfg.com'),
  ('c1000001-0000-0000-0000-000000000013', 'Windy City Tools', NULL, 'https://windycity-tools.com'),
  ('c1000001-0000-0000-0000-000000000014', 'Queen City Metals', NULL, 'https://queencity-metals.com'),
  ('c1000001-0000-0000-0000-000000000015', 'Crossroads Logistics', NULL, 'https://crossroads-logistics.com');

-- Insert Jobs (25 total, distributed across 5 cities)

-- Columbus, OH Jobs (5)
INSERT INTO jobs (company_id, slug, title, city, state, salary_min, salary_max, job_type, description, requirements, apply_url, territory, travel_percentage, industry_vertical, posted_at) VALUES
(
  'c1000001-0000-0000-0000-000000000001',
  'senior-industrial-sales-manager-acme-manufacturing',
  'Senior Industrial Sales Manager',
  'Columbus', 'OH',
  120000, 160000,
  'full-time',
  'Lead our industrial sales team and drive growth in the Midwest region. You will be responsible for developing strategic partnerships with manufacturing companies and expanding our market presence.',
  ARRAY['10+ years of industrial sales experience', 'Proven track record of exceeding sales targets', 'Experience managing a sales team of 5+', 'Strong knowledge of manufacturing processes', 'Bachelor''s degree in Business or Engineering'],
  'https://acme-manufacturing.com/careers/senior-sales-manager',
  'Midwest (OH, IN, MI, KY)',
  40,
  'Manufacturing Equipment',
  NOW() - INTERVAL '3 days'
),
(
  'c1000001-0000-0000-0000-000000000010',
  'territory-account-manager-buckeye-industrial',
  'Territory Account Manager',
  'Columbus', 'OH',
  75000, 95000,
  'full-time',
  'Manage and grow accounts in the Central Ohio territory. Build relationships with manufacturing facilities and distribution centers to drive MRO and industrial supply sales.',
  ARRAY['3+ years B2B sales experience', 'Experience with CRM systems', 'Strong presentation skills', 'Valid driver''s license', 'Self-motivated with entrepreneurial mindset'],
  'https://buckeye-industrial.com/careers/territory-am',
  'Central Ohio',
  50,
  'Industrial Supplies',
  NOW() - INTERVAL '5 days'
),
(
  'c1000001-0000-0000-0000-000000000004',
  'technical-sales-engineer-precision-tools-columbus',
  'Technical Sales Engineer',
  'Columbus', 'OH',
  85000, 115000,
  'full-time',
  'Combine your engineering background with sales skills to help customers find the right precision tooling solutions for their manufacturing needs.',
  ARRAY['Engineering degree or equivalent technical experience', '3+ years in technical sales or applications engineering', 'Knowledge of CNC machining and tooling', 'Strong analytical and problem-solving skills', 'Excellent communication abilities'],
  'https://precision-tools.com/jobs/sales-engineer-columbus',
  NULL,
  30,
  'Precision Tooling',
  NOW() - INTERVAL '2 days'
),
(
  'c1000001-0000-0000-0000-000000000007',
  'automation-sales-representative-automate-columbus',
  'Automation Sales Representative',
  'Columbus', 'OH',
  80000, 110000,
  'full-time',
  'Sell industrial automation solutions including PLCs, sensors, and motion control products to manufacturing customers throughout Ohio.',
  ARRAY['5+ years technical sales experience', 'Knowledge of industrial automation products', 'Experience with Rockwell, Siemens, or similar platforms', 'Technical aptitude for complex solutions', 'Hunter mentality with proven prospecting skills'],
  'https://automate-industries.com/careers/sales-rep-oh',
  'Ohio',
  45,
  'Industrial Automation',
  NOW() - INTERVAL '1 day'
),
(
  'c1000001-0000-0000-0000-000000000003',
  'inside-sales-specialist-industrial-supply-columbus',
  'Inside Sales Specialist',
  'Columbus', 'OH',
  55000, 70000,
  'full-time',
  'Handle inbound sales inquiries and support outside sales team. Process quotes, manage customer relationships, and identify upsell opportunities.',
  ARRAY['2+ years inside sales experience', 'Strong phone and email communication', 'Experience with ERP systems', 'Detail-oriented with strong follow-through', 'Knowledge of industrial products preferred'],
  'https://industrial-supply.com/careers/inside-sales',
  NULL,
  0,
  'Industrial Supplies',
  NOW() - INTERVAL '7 days'
);

-- Chicago, IL Jobs (5)
INSERT INTO jobs (company_id, slug, title, city, state, salary_min, salary_max, job_type, description, requirements, apply_url, territory, travel_percentage, industry_vertical, posted_at) VALUES
(
  'c1000001-0000-0000-0000-000000000003',
  'territory-sales-rep-industrial-supply-chicago',
  'Territory Sales Representative',
  'Chicago', 'IL',
  70000, 95000,
  'full-time',
  'Manage and grow sales in the Greater Chicago area. Sell industrial supplies, MRO products, and safety equipment to manufacturing facilities.',
  ARRAY['2+ years of outside sales experience', 'Valid driver''s license and reliable transportation', 'Strong relationship-building skills', 'Self-motivated with ability to work independently', 'Experience with industrial or MRO sales preferred'],
  'https://industrial-supply.com/careers/territory-rep-chicago',
  'Greater Chicago',
  60,
  'Industrial Supplies & MRO',
  NOW() - INTERVAL '6 days'
),
(
  'c1000001-0000-0000-0000-000000000013',
  'cutting-tools-specialist-windy-city-tools',
  'Cutting Tools Sales Specialist',
  'Chicago', 'IL',
  90000, 120000,
  'full-time',
  'Specialize in selling cutting tools and tooling systems to aerospace and automotive manufacturers in the Chicago metropolitan area.',
  ARRAY['5+ years cutting tool sales experience', 'Deep knowledge of carbide and HSS tooling', 'Experience with aerospace or automotive manufacturing', 'Technical background in machining', 'Established customer relationships preferred'],
  'https://windycity-tools.com/careers/cutting-tools-specialist',
  'Chicago Metro',
  40,
  'Cutting Tools',
  NOW() - INTERVAL '4 days'
),
(
  'c1000001-0000-0000-0000-000000000009',
  'material-handling-sales-great-lakes-chicago',
  'Material Handling Equipment Sales',
  'Chicago', 'IL',
  85000, 115000,
  'full-time',
  'Sell forklifts, conveyors, and warehouse automation solutions to distribution centers and manufacturing facilities in Illinois.',
  ARRAY['4+ years material handling sales experience', 'Knowledge of Toyota, Crown, or similar forklift brands', 'Experience with warehouse automation', 'Strong negotiation skills', 'Ability to manage complex sales cycles'],
  'https://greatlakes-equipment.com/careers/mh-sales-chicago',
  'Northern Illinois',
  50,
  'Material Handling',
  NOW() - INTERVAL '8 days'
),
(
  'c1000001-0000-0000-0000-000000000005',
  'packaging-solutions-consultant-midwest-packaging-chicago',
  'Packaging Solutions Consultant',
  'Chicago', 'IL',
  75000, 100000,
  'full-time',
  'Consult with food and beverage manufacturers on packaging equipment and solutions. Help customers improve efficiency and reduce costs.',
  ARRAY['3+ years packaging industry experience', 'Knowledge of packaging machinery and materials', 'Consultative sales approach', 'Experience with food and beverage manufacturing', 'Strong presentation and demo skills'],
  'https://midwest-packaging.com/careers/consultant-chicago',
  'Illinois & Wisconsin',
  45,
  'Packaging & Processing',
  NOW() - INTERVAL '10 days'
),
(
  'c1000001-0000-0000-0000-000000000008',
  'steel-products-sales-steel-dynamics-chicago',
  'Steel Products Sales Representative',
  'Chicago', 'IL',
  80000, 105000,
  'full-time',
  'Sell steel products including flat-rolled, structural, and specialty steels to fabricators and OEMs throughout the Midwest.',
  ARRAY['3+ years steel or metals sales experience', 'Knowledge of steel specifications and grades', 'Experience with contract negotiations', 'Strong market knowledge', 'Ability to manage price volatility discussions'],
  'https://steel-dynamics.com/careers/sales-chicago',
  'Midwest Region',
  35,
  'Steel & Metals',
  NOW() - INTERVAL '12 days'
);

-- Detroit, MI Jobs (5)
INSERT INTO jobs (company_id, slug, title, city, state, salary_min, salary_max, job_type, description, requirements, apply_url, territory, travel_percentage, industry_vertical, posted_at) VALUES
(
  'c1000001-0000-0000-0000-000000000002',
  'automation-sales-specialist-robotech-detroit',
  'Automation Sales Specialist',
  'Detroit', 'MI',
  95000, 130000,
  'full-time',
  'Sell cutting-edge automation and robotics solutions to automotive and manufacturing clients. Join a fast-growing company at the forefront of industrial automation.',
  ARRAY['5+ years of technical sales experience', 'Knowledge of industrial automation systems', 'Experience with CRM software', 'Excellent presentation skills', 'Ability to understand and explain technical concepts'],
  'https://robotech-solutions.com/jobs/automation-sales',
  'Michigan & Northern Ohio',
  50,
  'Automation & Robotics',
  NOW() - INTERVAL '1 day'
),
(
  'c1000001-0000-0000-0000-000000000011',
  'automotive-tier-1-account-manager-motor-city',
  'Automotive Tier-1 Account Manager',
  'Detroit', 'MI',
  110000, 145000,
  'full-time',
  'Manage relationships with major automotive Tier-1 suppliers. Drive sales of automation and assembly solutions for automotive production lines.',
  ARRAY['8+ years automotive industry sales experience', 'Established relationships with Tier-1 suppliers', 'Knowledge of automotive manufacturing processes', 'Experience with multi-year contracts', 'Strong project management skills'],
  'https://motorcity-automation.com/careers/tier1-am',
  'Michigan',
  40,
  'Automotive Automation',
  NOW() - INTERVAL '3 days'
),
(
  'c1000001-0000-0000-0000-000000000006',
  'heavy-equipment-sales-contract-detroit',
  'Heavy Equipment Sales (Contract)',
  'Detroit', 'MI',
  75000, 100000,
  'contract',
  '6-month contract position to support a major equipment rollout. Ideal for experienced sales professionals looking for project-based work.',
  ARRAY['5+ years of industrial equipment sales', 'Experience with heavy machinery or construction equipment', 'Strong negotiation skills', 'Available for immediate start', 'Willingness to travel extensively'],
  'https://heavy-machinery.com/contract-sales',
  NULL,
  70,
  'Heavy Machinery',
  NOW()
),
(
  'c1000001-0000-0000-0000-000000000004',
  'cnc-tooling-sales-precision-tools-detroit',
  'CNC Tooling Sales Representative',
  'Detroit', 'MI',
  80000, 105000,
  'full-time',
  'Sell precision CNC tooling to automotive and aerospace machine shops in the Detroit area. Strong technical support and training provided.',
  ARRAY['3+ years tooling sales experience', 'CNC machining knowledge required', 'Experience calling on machine shops', 'Technical aptitude', 'Self-starter with territory management skills'],
  'https://precision-tools.com/careers/cnc-sales-detroit',
  'Southeast Michigan',
  45,
  'Precision Tooling',
  NOW() - INTERVAL '5 days'
),
(
  'c1000001-0000-0000-0000-000000000009',
  'industrial-truck-sales-great-lakes-detroit',
  'Industrial Truck Sales Representative',
  'Detroit', 'MI',
  70000, 95000,
  'full-time',
  'Sell industrial trucks and material handling equipment to manufacturing and distribution customers. Territory includes Metro Detroit and surrounding areas.',
  ARRAY['2+ years equipment sales experience', 'Mechanical aptitude', 'Strong prospecting skills', 'Valid driver''s license', 'Experience with financing and leasing'],
  'https://greatlakes-equipment.com/careers/truck-sales-detroit',
  'Metro Detroit',
  55,
  'Material Handling',
  NOW() - INTERVAL '9 days'
);

-- Cincinnati, OH Jobs (5)
INSERT INTO jobs (company_id, slug, title, city, state, salary_min, salary_max, job_type, description, requirements, apply_url, territory, travel_percentage, industry_vertical, posted_at) VALUES
(
  'c1000001-0000-0000-0000-000000000014',
  'metals-sales-manager-queen-city-cincinnati',
  'Metals Sales Manager',
  'Cincinnati', 'OH',
  100000, 135000,
  'full-time',
  'Lead the sales team for our Cincinnati operation. Manage key accounts and develop new business in the tri-state area for specialty metals and alloys.',
  ARRAY['7+ years metals industry experience', '3+ years sales management experience', 'Knowledge of specialty metals and alloys', 'P&L management experience', 'Strategic planning abilities'],
  'https://queencity-metals.com/careers/sales-manager',
  'OH, KY, IN Tri-State',
  30,
  'Metals & Alloys',
  NOW() - INTERVAL '4 days'
),
(
  'c1000001-0000-0000-0000-000000000001',
  'manufacturing-equipment-sales-acme-cincinnati',
  'Manufacturing Equipment Sales',
  'Cincinnati', 'OH',
  85000, 115000,
  'full-time',
  'Sell manufacturing equipment and machinery to consumer products and pharmaceutical manufacturers in the Greater Cincinnati region.',
  ARRAY['5+ years capital equipment sales', 'Experience with consumer products or pharma manufacturing', 'Strong technical aptitude', 'Consultative selling skills', 'Ability to manage long sales cycles'],
  'https://acme-manufacturing.com/careers/equipment-sales-cincy',
  'Greater Cincinnati',
  40,
  'Manufacturing Equipment',
  NOW() - INTERVAL '6 days'
),
(
  'c1000001-0000-0000-0000-000000000005',
  'packaging-equipment-sales-midwest-packaging-cincinnati',
  'Packaging Equipment Sales',
  'Cincinnati', 'OH',
  80000, 110000,
  'full-time',
  'Sell packaging lines and equipment to food, beverage, and consumer products manufacturers. Focus on complete line solutions from primary packaging to palletizing.',
  ARRAY['4+ years packaging equipment sales', 'Knowledge of packaging machinery', 'Experience with capital equipment sales cycles', 'Technical presentation skills', 'Willingness to travel for trade shows'],
  'https://midwest-packaging.com/careers/equipment-sales-cincy',
  'Ohio & Kentucky',
  45,
  'Packaging Equipment',
  NOW() - INTERVAL '11 days'
),
(
  'c1000001-0000-0000-0000-000000000003',
  'industrial-safety-sales-industrial-supply-cincinnati',
  'Industrial Safety Sales Representative',
  'Cincinnati', 'OH',
  65000, 85000,
  'full-time',
  'Specialize in selling safety products and PPE to manufacturing facilities. Help companies improve workplace safety while meeting compliance requirements.',
  ARRAY['2+ years safety products sales experience', 'Knowledge of OSHA requirements', 'Strong relationship building skills', 'Experience with safety audits preferred', 'Self-motivated with territory management skills'],
  'https://industrial-supply.com/careers/safety-sales-cincy',
  'Southwest Ohio',
  50,
  'Safety Products',
  NOW() - INTERVAL '8 days'
),
(
  'c1000001-0000-0000-0000-000000000007',
  'process-automation-sales-automate-cincinnati',
  'Process Automation Sales Engineer',
  'Cincinnati', 'OH',
  90000, 120000,
  'full-time',
  'Sell process automation solutions to chemical, pharmaceutical, and food processing industries. Strong focus on instrumentation and control systems.',
  ARRAY['Engineering degree preferred', '5+ years process automation experience', 'Knowledge of DCS and PLC systems', 'Experience with process industries', 'Strong technical presentation skills'],
  'https://automate-industries.com/careers/process-sales-cincy',
  'Ohio Valley',
  35,
  'Process Automation',
  NOW() - INTERVAL '2 days'
);

-- Indianapolis, IN Jobs (5)
INSERT INTO jobs (company_id, slug, title, city, state, salary_min, salary_max, job_type, description, requirements, apply_url, territory, travel_percentage, industry_vertical, posted_at) VALUES
(
  'c1000001-0000-0000-0000-000000000005',
  'regional-sales-director-midwest-packaging-indianapolis',
  'Regional Sales Director',
  'Indianapolis', 'IN',
  140000, 180000,
  'full-time',
  'Lead our regional sales organization and drive revenue growth across the Midwest. Manage a team of 8 sales representatives and develop strategic customer relationships.',
  ARRAY['15+ years of B2B sales experience', '5+ years of sales leadership experience', 'Experience in packaging or related industries', 'Strategic planning and execution skills', 'MBA preferred'],
  'https://midwest-packaging.com/careers/regional-director',
  'Midwest Region',
  35,
  'Packaging & Processing',
  NOW() - INTERVAL '11 days'
),
(
  'c1000001-0000-0000-0000-000000000012',
  'manufacturing-sales-rep-hoosier-mfg',
  'Manufacturing Sales Representative',
  'Indianapolis', 'IN',
  70000, 90000,
  'full-time',
  'Sell manufacturing services including CNC machining, fabrication, and assembly to OEMs throughout Indiana. Great opportunity for someone passionate about manufacturing.',
  ARRAY['3+ years outside sales experience', 'Knowledge of manufacturing processes', 'Mechanical aptitude', 'Strong prospecting and closing skills', 'Experience with technical products'],
  'https://hoosier-mfg.com/careers/sales-rep',
  'Indiana',
  55,
  'Contract Manufacturing',
  NOW() - INTERVAL '7 days'
),
(
  'c1000001-0000-0000-0000-000000000015',
  'logistics-solutions-sales-crossroads-indianapolis',
  'Logistics Solutions Sales Executive',
  'Indianapolis', 'IN',
  85000, 115000,
  'full-time',
  'Sell integrated logistics and supply chain solutions to manufacturing and distribution companies. Indianapolis is the crossroads of America - leverage this advantage.',
  ARRAY['5+ years logistics or supply chain sales', 'Understanding of 3PL and warehousing services', 'Experience with enterprise sales', 'Strong business acumen', 'Relationship-driven sales approach'],
  'https://crossroads-logistics.com/careers/solutions-sales',
  'Central US',
  40,
  'Logistics & Supply Chain',
  NOW() - INTERVAL '3 days'
),
(
  'c1000001-0000-0000-0000-000000000002',
  'robotics-integration-sales-robotech-indianapolis',
  'Robotics Integration Sales',
  'Indianapolis', 'IN',
  95000, 125000,
  'full-time',
  'Sell robotic workcells and integration services to automotive suppliers and general manufacturing. Join the robotics revolution in the heart of manufacturing country.',
  ARRAY['5+ years automation or robotics sales', 'Technical background in robotics', 'Experience with FANUC, ABB, or similar', 'Project-based selling experience', 'Strong technical presentation skills'],
  'https://robotech-solutions.com/careers/integration-sales-indy',
  'Indiana & Kentucky',
  45,
  'Robotics Integration',
  NOW() - INTERVAL '5 days'
),
(
  'c1000001-0000-0000-0000-000000000010',
  'industrial-supplies-account-exec-buckeye-indianapolis',
  'Industrial Supplies Account Executive',
  'Indianapolis', 'IN',
  65000, 85000,
  'full-time',
  'Grow sales of industrial supplies and MRO products in the Indianapolis market. Focus on manufacturing facilities and distribution operations.',
  ARRAY['2+ years B2B sales experience', 'Knowledge of industrial products helpful', 'Strong cold-calling and prospecting skills', 'CRM proficiency', 'Goal-oriented with competitive drive'],
  'https://buckeye-industrial.com/careers/account-exec-indy',
  'Greater Indianapolis',
  45,
  'Industrial Supplies',
  NOW() - INTERVAL '9 days'
);
